### ISSUE TITLE
websocket: close 1006 (abnormal closure): unexpected EOF

### ISSUE THREAD

**Issue by hazcod** [CaliDog/certstream-go#8] opened 2019-08-04 13:01 UTC
Hi, I frequently get these errors and suspect it might have something to do with `HandshakeTimeout` 45 being too low?
```
2019/08/04 14:55:20 ERROR: Error decoding json frame!: websocket: close 1006 (abnormal closure): unexpected EOF
2019/08/04 14:56:12 ERROR: Error decoding json frame!: websocket: close 1006 (abnormal closure): unexpected EOF
2019/08/04 14:57:12 ERROR: Error decoding json frame!: websocket: close 1006 (abnormal closure): unexpected EOF
2019/08/04 14:58:13 ERROR: Error decoding json frame!: websocket: close 1006 (abnormal closure): unexpected EOF
2019/08/04 14:59:14 ERROR: Error decoding json frame!: websocket: close 1006 (abnormal closure): unexpected EOF
2019/08/04 14:59:58 ERROR: Error decoding json frame!: websocket: close 1006 (abnormal closure): unexpected EOF
```

```
package certstream

import (
	"time"
	"github.com/gorilla/websocket"
	"github.com/jmoiron/jsonq"
	"github.com/pkg/errors"
)

func CertStreamEventStream(skipHeartbeats bool) (chan jsonq.JsonQuery, chan error) {
	outputStream := make(chan jsonq.JsonQuery)
	errStream := make(chan error)

	go func() {
		for {
			c, _, err := websocket.DefaultDialer.Dial("wss://certstream.calidog.io", nil)

			if err != nil {
				errStream <- errors.Wrap(err, "Error connecting to certstream! Sleeping a few seconds and reconnecting... ")
				time.Sleep(5 * time.Second)
				continue
			}

			defer c.Close()
			defer close(outputStream)

			for {
				var v interface{}
				err = c.ReadJSON(&v)
				if err != nil {
					errStream <- errors.Wrap(err, "Error decoding json frame!")
					c.Close()
					break
				}

				jq := jsonq.NewQuery(v)

				res, err := jq.String("message_type")
				if err != nil {
					errStream <- errors.Wrap(err, "Could not create jq object. Malformed json input recieved. Skipping.")
					continue
				}

				if skipHeartbeats && res == "heartbeat" {
					continue
				}

				outputStream <- *jq
			}
		}
	}()

	return outputStream, errStream
}
```

**Comment by melenlu** [comment] 2019-12-02 09:10
I get the same error. And tried to configure Dailer with a bigger handshake but it didn't help. It looks like connection to wss://certstream.calidog.io is periodically  being lost while a message fragment is already written. So we get EOF in Reader.

**Comment by Fitblip** [comment] 2019-12-20 04:11
Hey folks, sorry for the delay here.

Digging into this, it looks like cowboy (the underlying websocket server for certstream) will timeout connections after a minute and force reconnection - https://github.com/ninenines/cowboy/issues/1259

I didn't realize this and figured another mechanism would be handling heartbeats, which doesn't seem to be the case. I'm going to add heartbeating to this and the clients which should (hopefully) remedy these issues (the python client is experiencing this as well - https://github.com/CaliDog/certstream-python/issues/27).

**Comment by hazcod** [comment] 2019-12-24 09:35
https://github.com/CaliDog/certstream-python/issues/27 seems to be fixed, can we port this to go?

**Comment by Fitblip** [comment] 2019-12-25 06:46
Howdy @hazcod - I actually spent some time attempting to do this, but after battling path issues with my golang install, reading through gorilla docs and super confusing examples (apparently which [don't use the DefaultDialer](https://github.com/gorilla/websocket/search?q=websocket.DefaultDialer&unscoped_q=websocket.DefaultDialer)?), and tinkering with things I'm at a point where I don't wish to spend any more time on this. 

I don't use this integration with any of my personal projects but if you (or anyone else for that matter) would like to take a stab at implementing/fixing this bug that'd be greatly appreciated! PRs are definitely welcome.

Merry Christmas!
Ryan

**Comment by klausenbusk** [comment] 2019-12-28 19:50
I just tried to fix this (see my `fixs` branch: https://github.com/CaliDog/certstream-go/compare/master...klausenbusk:fixs), by adding Read/Write deadlines and a periodic "keep-alive".

It doesn't work as the server responds very slowly to pings. @Fitblip do you have any idea what is going on?

```
new
2019/12/28 20:40:46 ping
2019/12/28 20:40:46 ping2 <nil>
2019/12/28 20:40:59 pong
2019/12/28 20:41:01 ping
2019/12/28 20:41:01 ping2 <nil>
2019/12/28 20:41:16 ping
2019/12/28 20:41:16 ping2 <nil>
new
2019/12/28 20:41:29 Error decoding json frame!: websocket: close 1006 (abnormal closure): unexpected EOF
done
2019/12/28 20:41:44 ping
2019/12/28 20:41:44 ping2 <nil>
2019/12/28 20:41:51 pong
2019/12/28 20:41:59 ping
2019/12/28 20:41:59 ping2 <nil>
2019/12/28 20:42:14 ping
2019/12/28 20:42:14 ping2 <nil>
new
2019/12/28 20:42:21 Error decoding json frame!: websocket: close 1006 (abnormal closure): unexpected EOF
done
```

**Comment by alsyia** [comment] 2020-04-22 14:49
I just made a PR to fix this, as you said PR were welcome. I took inspiration from @klausenbusk code although I didn't put a write timeout because I was not sure what it was used for. 

I can confirm the official server responds very slowly to pings, sometimes disconnecting clients because it thinks they are dead. I've been using this Go client with my own Certstream instance for a few weeks though, and with the changes on heartbeats and read timeouts, I haven't had any issue since.

**Comment by Fitblip** [comment] 2020-07-13 03:16
@alsyia massive thanks for the PR to fix this, it’s been merged so folks shouldn’t see any more connection issues 👍

**Closed as completed by Fitblip** 2020-07-13 03:16 UTC

**Comment by alsyia** [comment] 2020-07-15 12:10
Great, thanks for your time :)

**Comment by rverton** [comment] 2021-08-25 12:24
I still get this same error with the latest fix in irregular intervals. Was there some change in the backend or is the bug not triggered for you currently @alsyia ?

```
INFO[1184] error Error decoding json frame!: websocket: close 1006 (abnormal closure): unexpected EOF
INFO[1281] error Error decoding json frame!: websocket: close 1006 (abnormal closure): unexpected EOF
INFO[1473] error Error decoding json frame!: websocket: close 1006 (abnormal closure): unexpected EOF
INFO[2051] error Error decoding json frame!: websocket: close 1006 (abnormal closure): unexpected EOF
INFO[2192] error Error decoding json frame!: websocket: close 1006 (abnormal closure): unexpected EOF
```

**Comment by alsyia** [comment] 2021-09-13 14:39
Hi @rverton! At the moment I don't see any issue, but as stated above I have my own Certstream server because I found the official/public one to be quite unreliable.

Hope that helps!
